version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: librechat-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: LibreChat
    networks:
      - librechat-network
    command: mongod --bind_ip_all
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: librechat-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - librechat-network
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  meilisearch:
    image: getmeili/meilisearch:v1.12.3
    container_name: librechat-meilisearch
    restart: unless-stopped
    ports:
      - "7700:7700"
    environment:
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY:-DrhYf7zENyR6AlUCKmnz0eYASOQdl6zxH7s7MKFSfFCt}
      MEILI_NO_ANALYTICS: true
      MEILI_ENV: production
      MEILI_LOG_LEVEL: INFO
    volumes:
      - meilisearch_data:/meili_data
    networks:
      - librechat-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7700/health"]
      interval: 10s
      timeout: 3s
      retries: 5

  librechat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: librechat-app
    restart: unless-stopped
    ports:
      - "3080:3080"
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
      meilisearch:
        condition: service_healthy
    volumes:
      - ./logs:/app/api/logs
      - ./images:/app/client/public/images
      - ./uploads:/app/uploads
      - ./.env:/app/.env:ro
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3080
      - MONGO_URI=mongodb://mongodb:27017/LibreChat
      - REDIS_URI=redis://redis:6379
      - MEILI_HOST=http://meilisearch:7700
      - USE_REDIS=true
    networks:
      - librechat-network
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G

  nginx:
    image: nginx:alpine
    container_name: librechat-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites-available:/etc/nginx/sites-available:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - nginx_cache:/var/cache/nginx
    depends_on:
      - librechat
    networks:
      - librechat-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mongodb_data:
  redis_data:
  meilisearch_data:
  nginx_cache:

networks:
  librechat-network:
    driver: bridge